/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE exameBaseService PLEASE EDIT ../exame.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exame } from '../../domain/schoolprova_db/exame';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../exame.service.ts
 */

/*
 * SCHEMA DB exame
 *
	{
		place: {
			type: 'String'
		},
		score: {
			type: 'Number'
		},
		valide: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_course: {
			type: Schema.ObjectId,
			ref : "exame"
		},
		_student: {
			type: Schema.ObjectId,
			ref : "exame"
		},
		_teacher: {
			type: Schema.ObjectId,
			ref : "exame"
		},
	}
 *
 */
@Injectable()
export class ExameBaseService {

    contextUrl: string = environment.endpoint + '/exame';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * exameService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exame): Observable<Exame> {
        return this.http
            .post<Exame>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * exameService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * exameService.findBy_course
    *   @description CRUD ACTION findBy_course
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_course(id: string): Observable<Exame[]> {
        return this.http
            .get<Exame[]>(this.contextUrl + '/findBy_course/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * exameService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<Exame[]> {
        return this.http
            .get<Exame[]>(this.contextUrl + '/findBy_student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * exameService.findBy_teacher
    *   @description CRUD ACTION findBy_teacher
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_teacher(id: string): Observable<Exame[]> {
        return this.http
            .get<Exame[]>(this.contextUrl + '/findBy_teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * exameService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Exame> {
        return this.http
            .get<Exame>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * exameService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exame[]> {
        return this.http
            .get<Exame[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * exameService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Exame): Observable<Exame> {
        return this.http
            .post<Exame>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs


    /**
    * exameService.validate
    *   @description This API is use to validate the exam
    *   @param String id id of the exam
    *   @returns Boolean
    *
    */
    validate(...params: any[]): Observable<any> {
        return this.http
            .post<any>(this.contextUrl + '/{id}/validate', {})
            .pipe(
                map(response => response)
            );
    }

}
